accounts/urls.py
from django.urls import path

from accounts import views
from django.contrib.auth import views as auth_views

from accounts.views import VendorView, CreatePostView, CartView, ProfileView, VProfileView, CartDisplayView

app_name = 'accounts'

urlpatterns = [
    path('registration', views.UserCreateView.as_view(), name='user-create'),
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('logged_out', auth_views.LogoutView.as_view(), name='logged-out'),
    path('check_unique', views.check_username_is_unique, name='check-username-unique'),
    path('<pk>/', VendorView.as_view(), name='vendor_detail'),
    path('<pk>/post', CreatePostView.as_view(), name='add_post'),
    path('cart', CartView.as_view(), name='cart'),
    path('buy', views.buy_cart, name='buy'),
    path('user_profile', ProfileView.as_view(), name='user_profile'),
    path('vendor_profile', VProfileView.as_view(), name='vendor_profile'),
    path('cart_display/<pk>', CartDisplayView.as_view(), name='cart_display')


]

cards/urls.py
from django.urls import path

from django.urls import path

from .views import CreateCardView, CardDetailView, add_to_cart, remove_from_cart

app_name = 'card'

urlpatterns = [
    path('', CreateCardView.as_view(), name='add_card'),
    path('<pk>/', CardDetailView.as_view(), name='card_detail'),
    path('<pk>/add_to_cart/', add_to_cart, name='add_to_cart'),
    path('<pk>/remove_from_cart/', remove_from_cart, name='remove_from_cart')
    # se vuoi vedere esattamente un oggetto serve un
    # pk nell'url
]

esame_TC/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from esame_TC.views import HomePageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePageView.as_view(), name='homepage'),
    path('accounts/', include('accounts.urls')),
    path('card/', include('cards.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/CardDetail.html
{% extends 'base.html' %}#

{% load static %}

{% block title %} Test {% endblock %}

{% block content %}
{% comment %}<link rel="stylesheet" type="text/css" href="{% static 'css/carddetail.css' %}"> {% endcomment %}
<link rel="stylesheet" href="{% static 'css/carddetail.css' %}">
<h2>Nome carta: {{ Card.name }}</h2>
<h2>Nome set: {{ Card.set}}</h2>
<h2>Prezzo carta: {{ Card.price }}</h2>
<h2>Venditore: {{ Card.vendor}}</h2>
<img src="{{ Card.image.url}}" alt="{{ Card.name }}">

{% if request.user.profile.is_vendor %}
{% else %}
<a class="btn btn-primary" href="{% url 'card:add_to_cart' pk=Card.id %}"> Add to cart </a>
<a class="btn btn-danger" href="{% url 'card:remove_from_cart' pk=Card.id %}"> Remove from cart </a>
{% endif %}

<div class="mt-5 pt-4">
<h2>Prodotti simili</h2>
<div class="grid-container">
{% for item in raccomendations %}
<div class="grid-item">
<h2>{{ item.name }}</h2>
<img src="{{ item.image.url}}" alt="{{ item.name }}">
</div>
{% endfor %}
</div>
</div>
{% endblock %}

templates/VendorDetail.html
{% extends 'base.html' %}#

{% load static %}

{% block title %} Test {% endblock %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/vendordetail.css' %}">
<h2>Username: {{ Vendor.username }}</h2>
<div class="mt-5 pt-4">
<h2>Valutazioni e commenti</h2>
</div>
{% if request.user.is_authenticated %}
<div class="mt-5 pt-4">
<p>  Submit: <a class="btn btn-primary" href="{% url 'accounts:add_post' pk=Vendor.id %}"> Scrivi Post </a>  </p>
</div>
{% endif %}
<div class="grid-container">
{% for post in listapost %}
<div class="grid-item">
  <h2>{{ post.author }}</h2>
  <p>{{ post.title }}</p>
  <p>{{ post.body }}</p>
  <span class="time-left">{{ post.date }}</span>
</div>
{% endfor %}
</div>


{% endblock %}

templates/base.html
{% comment %} posso scrivere qualsiasi commento
starter template copincollato da bootstrap
{% endcomment %}

{% load static %}

<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.21/datatables.min.css" />

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
      integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>


    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.21/datatables.min.js"></script>
    <title>CARD KINGDOM</title>
</head>

   <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">


    <a href="/"><img  style="width: 6rem;"  src="https://3dprint.com/wp-content/uploads/2016/03/3dp_mtgtokens_magic_logo.png"></a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <div class="container">

            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link text-dark" href="{% url 'homepage' %}">Home<span class="sr-only">(current)</span></a>
                </li>

                {% if request.user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ request.user.username }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% if request.user.profile.is_vendor %}
                            <a class="dropdown-item" href="{% url 'accounts:vendor_profile' %}">Profilo</a>
                            <a class="dropdown-item" href="{% url 'card:add_card' %}">Vendi carte</a>
                            {% else %}
                            <a class="dropdown-item" href="{% url 'accounts:user_profile' %}">Profilo</a>
                            <a class="dropdown-item" href="{% url 'accounts:cart' %}">Cart</a>
                            {% endif %}
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item text-dark" href="{% url 'accounts:logged-out' %}">Esci</a>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link text-dark" href="{% url 'accounts:user-create' %}">Registrazione</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" href="{% url 'accounts:login' %}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>

<div class="mt-5 pt-4">
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
        </div>
    {% endfor %}
{% endif %}
</div>

</nav>

    <div id = "site-main-page" class = "container mt-3 pt-3">
         {% block content %}

         {% endblock %}
    </div>



     {% block javascript %}

    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.21/datatables.min.js%22%3E"> </script>

     {% endblock %}


  </body>
</html>

templates/cart.html
{% extends 'base.html' %}#
{% load static %}
{% block javascript %}

   <script src="https://cdn.jsdelivr.net/npm/easytimer@1.1.1/dist/easytimer.min.js"></script>
   <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
   <script src="{% static 'js/home.js' %}"></script>

{% endblock %}
{% block title %}Cart{% endblock %}

{% block content %}

<h1>Riassunto ordine</h1>
<div>
<table class="table"  id="OrderTable">
    <thead>
        <tr>
            <th> Name </th>
            <th> Set </th>
            <th> Vendor </th>
            <th> Price </th>
            <th> Quantity </th>
            <th> Total Price </th>
        </tr>
    </thead>

    <tbody>
        {% for Card_order in object.items.all %}
        <tr>
            <td><a href="{% url 'card:card_detail' pk=Card_order.card.id %}">{{ Card_order.card.name }}</a></td>
            <td>{{ Card_order.card.set }}</td>
            <td><a href="{% url 'accounts:vendor_detail' pk=Card_order.card.vendor.id %}">{{ Card_order.card.vendor }}</a></td>
            <td>{{ Card_order.card.price }}</td>
            <th>{{ Card_order.quantity }}</th>
            <th>{{ Card_order.get_tot_price }}</th>
        </tr>
        {% endfor %}
            {% if object.get_total %}
        <tr>
            <td colspan="4"><b>Order Total</b></td>
            <td><b>${{ object.get_total }}</b></td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-warning float-right ml-2' href="{% url 'accounts:buy' %}">Proceed to checkout</a>
    {% comment %}        <a class='btn btn-primary float-right' href="{% url 'homepage' %}">Continue shopping</a>       {% endcomment %}
            </td>
        </tr>
        {% endif %}
    </tbody>
</table>




</div>



{% endblock %}

templates/cartdisplay.html
{% extends 'base.html' %}#

{% load static %}
{% block content %}
<h1>Oggetti nel carrello</h1>
<div>
<table class="table"  id="aTable">
    <thead>
        <tr>
            <th> Oggetto </th>
            <th> Prezzo </th>
            <th> Quantità </th>
            <th> Venditore </th>
        </tr>
    </thead>

    <tbody>
        {% for item in listacquisti %}
        <tr>
            <td>{{ item.card.name }}</td>
            <td>{{ item.card.price }}</td>
            <td>{{ item.quantity }}</td>
            <td>{{ item.card.vendor }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>

{% endblock %}

templates/check-out.html
{% extends 'base.html' %}#
{% load static %}

{% block content %}



{% endblock %}

templates/home.html
{% extends 'base.html' %}#
{% load static %}

{% block title %}Homepage{% endblock %}
{% block javascript %}

   <script src="{% static 'js/home.js' %}"></script>

{% endblock %}
{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">

<h1>Carte in anteprima</h1>
<div class="grid-container">
{% for Card in prime %}
<div class="grid-item">
<h2><a href="{% url 'card:card_detail' pk=Card.id %}">{{ Card.name }}</a></h2>
<img src="{{ Card.image.url}}" alt="{{ Card.name }}">
    <h2>{{ Card.price }}</h2>
</div>
{% endfor %}
</div>

<h1>Carte in Vendita</h1>
<div>


<table class="table"  id="CardTable">
    <thead>
        <tr>
            <th> Name </th>
            <th> Set </th>
            <th> Vendor </th>
            <th> Price </th>
        </tr>
    </thead>

    <tbody>
        {% for Card in cards %}
        <tr>
            <td><a href="{% url 'card:card_detail' pk=Card.id %}">{{ Card.name }}</a></td>
            <td>{{ Card.set }}</td>
            <td><a href="{% url 'accounts:vendor_detail' pk=Card.vendor.id %}">{{ Card.vendor }}</a></td>
            <td>{{ Card.price }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>



</div>

{% if request.user.is_authenticated %}
   <p>  Logout: <a class="btn btn-primary" href="{% url 'accounts:logged-out' %}"> Logout </a>  </p>
{% else %}
   <p>  Registrazione: <a class="btn btn-primary" href="{% url 'accounts:user-create' %}"> Registrazione </a>  </p>
   <p>  Login: <a class="btn btn-primary" href="{% url 'accounts:login' %}"> Login </a>  </p>
   <p>  Logout: <a class="btn btn-primary" href="{% url 'accounts:logged-out' %}"> Logout </a>  </p>
{% endif %}

{% endblock %}

templates/post.html
{% extends 'base.html' %}#

{% load static %}

{% block title %} Test {% endblock %}

{% block content %}

<h1>Create Post Page</h1>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Submit New Post</button>
</form>

{% endblock %}

templates/sellcard.html
{% extends 'base.html' %}#

{% load static %}

{% block title %}Homepage{% endblock %}

{% block content %}

<h1>Sell Card</h1>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Vendi</button>
</form>

{% endblock %}

templates/userprofile.html
{% extends 'base.html' %}#

{% load static %}

{% block title %} Test {% endblock %}

{% block content %}

<h2>Username: {{ User.username }}</h2>
<h2>Email: {{ User.email }}</h2>
<div class="mt-5 pt-4">
<h2>Acquisti</h2>
</div>
<div>
<table class="table"  id="UserTable">
    <thead>
        <tr>
            <th> Numero d'Ordine </th>
            <th> Spesa </th>
        </tr>
    </thead>

    <tbody>
        {% for item in listacquisti %}
        <tr>
            <td><a href="{% url 'accounts:cart_display' pk=item.cart.id %}">{{ item.id }}</a></td>
            <td>{{ item.amount }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>


{% block javascript %}

   <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
   <script src="{% static 'js/user.js' %}"></script>

{% endblock %}

</div>


{% endblock %}

templates/vendorprofile.html
{% extends 'base.html' %}#

{% load static %}
{% block javascript %}

   <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
   <script src="{% static 'js/vendor.js' %}"></script>

{% endblock %}
{% block title %} Test {% endblock %}

{% block content %}

<h2>Username: {{ Vendor.username }}</h2>
<h2>Email: {{ Vendor.email }}</h2>

<div class="mt-5 pt-4">
<h2>Vendite</h2>
</div>

<div class="mt-5 pt-4">
<table class="table"  id="VendorTable">
    <thead>
        <tr>
            <th> Object </th>
            <th> Buyer </th>
            <th> Quantity </th>
            <th> Price </th>
            <th> Date </th>
        </tr>
    </thead>

    <tbody>
        {% for item in listavendite %}
        <tr>
            <td>{{ item.card.name }}</td>
            <td>{{ item.user }}</td>
            <td>{{ item.quantity }}</td>
            <td>{{ item.card.price }}</td>
            <td>{{ item.ordered_date }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>




</div>

{% endblock %}